### ISSUE TITLE
Get element position relative to window

### ISSUE THREAD

**Issue by rocodesign** [pc035860/angular-scroll-watch#14]
Hello.
I'm trying to get the top position of an element, $offsetTop seems to be relative to the container, is there a way I could get the element position relative to the window, (actual top position in the viewport)?

Thanks

**Comment by pc035860** [comment]
@rocodesign  Can you provide a usage example?

Currently there's no locals based on viewport position, will have to calculate some new locals for it.

**Comment by rocodesign** [comment]
http://plnkr.co/edit/zcbUueRqRVxKN0FleMrX?p=preview

Here's a fork of your example, also imagine that as soon as all items get near the top you want to make them smaller or something like that, each item needs to be aware of it's own position as it get's out of the area.

**Comment by pc035860** [comment]
I think implementing viewport locals is doable. But in your case, you're actually changing the targeted element's position (by making it fixed to top).

Most of the locals are calculated via the targeted element's position, so we'll have to figure out a way to save the **targeted element's position at certain moment**(web page is pretty dynamic).

You can also checkout angular-waypoints, see if it is close to what you want.
https://github.com/zumba/angular-waypoints
