### ISSUE TITLE
i need animation only once

### ISSUE THREAD

**Issue by tushariscoolster** [pc035860/angular-scroll-watch#4]
my code is

<section id="contact" class="white-bg contact animated" check="{{$percentage}}" scroll-watch="{from: 0, to: -1,digestSync: false}"
   sw-class="{
    zoomIn: $percentage > 80
  }"   >

But i want animationto be happend only once

**Comment by pc035860** [comment]
I would suggest using `sw-broadcast` with an addition scope variable as a flag for **once**, then use it with built-in `ng-class`.

e.g. (not tested)

```html
<!-- watcher -->
<div scroll-watch="{from: 499, to: 500}"
  sw-broadcast="{
    'hiiiiiit': '$percentage > 0'
  }">
</div>

<!-- item -->
<div class="animated-item" ng-class="{'in-view': animated}"></div>
```

```js
.controller('AppCtrl', function ($scope) {
    $scope.animated = false;

    $scope.$on('hiiiiiit', function () {
        $scope.animated = true;
    });
});
```

**Comment by tushariscoolster** [comment]
Thanks for your help
