### ISSUE TITLE
Availability on the NPM registry?

### ISSUE THREAD

**Issue by jbrunel** [pc035860/angular-scroll-watch#8]
Hello,

Will this, at some point, be available on the NPM registry?

Thanks!
Jerome

**Comment by pc035860** [comment]
Published!
https://www.npmjs.com/package/anguar-scroll-watch

**Comment by jbrunel** [comment]
Mate it is the wrong name ! `anguar` instead of `angular` ;)

**Comment by pc035860** [comment]
Ooops, thanks.

Re-published, and the old one is removed!
https://www.npmjs.com/package/angular-scroll-watch

**Comment by jbrunel** [comment]
Thanks!
